language: generic 
sudo: required
services: 
    - docker

before_install: 
    - docker build -t stephenharper82/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true stephenharper82/docker-react npm run test